### ISSUE TITLE
Why the inference results are so poor?

### ISSUE THREAD

**Issue by tmzcometolearn** [xyxingx/LumiNet#3]
Replace the input image path and reference image path, I run the relit_inference.py, but the results were not as expected. Why is this?
Input Image
<img width="1152" height="1536" alt="Image" src="https://github.com/user-attachments/assets/613ca442-4353-40b3-8d07-20f6dad0c4f2" />

Reference Image
![Image](https://github.com/user-attachments/assets/d3e36a1a-75c7-4744-993a-54ff311b1a6c)

Output
![Image](https://github.com/user-attachments/assets/6873ed6b-d6dc-4201-9c87-63b0618fe5be)

- Reference lighting is not perceived: hue, color temperature, etc.
- The quality of the raw image is very poor.

I hope to get the answer, thank you very much.

**Comment by xyxingx** [comment]
Hi, unfortunately, this type of lighting transfer is known as a typical failure mode in our paper (see Fig. 8 and the Limitations section). The model should perform well on more natural, modest relighting, for example, toggling a lamp on/off or letting the room be lit only by daylight through a window.

Regarding the aliasing you’re seeing in the relit result: it’s likely due to upscaling from the model’s working resolution (512×512) back to a much higher native resolution. The inference pipeline runs at 512×512 and then resizes to the original size, which can introduce aliasing. I’ve pushed a small fix to the inference code ([L104-112](https://github.com/xyxingx/LumiNet/blob/main/relit_inference.py#L104C1-L104C13)) to cap the output scale (while preserving aspect ratio) so we don’t upsample far beyond 512×512.

**Comment by tmzcometolearn** [comment]
@xyxingx Thanks for your reply, I prepare to test more examples.

**Comment by tmzcometolearn** [comment]
@xyxingx hello, I pull the newest code to run, but the generated result is still not good. It’s not a problem of upsampling, it’s blurry after denoising. I only update the source image path and target image path, so I don't know what the problem is.

![Image](https://github.com/user-attachments/assets/82523627-446c-4069-a1d7-714648cf4d34)
![Image](https://github.com/user-attachments/assets/9ed8faf8-bad8-41f5-b73d-ddde413d8063)
![Image](https://github.com/user-attachments/assets/d890fab3-10eb-4ea9-8d45-382ed03bd8cc)
![Image](https://github.com/user-attachments/assets/590f23f4-82a1-4989-99f4-e974ea6bcd35)
